# Generated by Django 5.0.7 on 2024-07-23 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_tutor',
            field=models.BooleanField(default=False, verbose_name='Student or Tutor'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='contact_no',
            field=models.CharField(default='', max_length=10, verbose_name='Contact Number'),
        ),
    ]
