# Generated by Django 5.0.7 on 2024-07-24 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_customuser_is_tutor_alter_customuser_contact_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=60, unique=True, verbose_name='Email Address'),
        ),
    ]
